edition = "2021"
enum_discrim_align_threshold = 999
format_code_in_doc_comments = true
format_generated_files = true
format_macro_bodies = true
format_macro_matchers = true
format_strings = true
hex_literal_case = "Lower"
imports_granularity = "Crate"
imports_layout = "HorizontalVertical"
max_width = 80
normalize_comments = true
normalize_doc_attributes = true
reorder_impl_items = true
struct_field_align_threshold = 999
unstable_features = true
use_small_heuristics = "Max"
version = "Two"
